apiVersion: v1
kind: Secret
metadata:
  name: gs-secrets
  namespace: geosentinel
type: Opaque
stringData:
  DB_PASSWORD: gs_secret
  REDIS_PASSWORD: gs_redis
  JWT_SECRET: gs_jwt_secret_256bits_padded_for_minimum_length_requirement
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gs-config
  namespace: geosentinel
data:
  DB_USER: geosentinel
  REDIS_HOST: redis-service
  KAFKA_BOOTSTRAP: kafka-service:9092
